config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'management#index'

  get 'dashboard' => 'dashboard#index', as: :dashboard

  get 'einkauf' => 'trades#index', as: :trades
  get 'vertrieb' => 'sales#index', as: :sales
  get 'produktion' => 'production#index', as: :production
  get 'lager' => 'storage#index', as: :storage
  get 'bericht' => 'reports#index', as: :reports
  get 'bank' => 'banking#index', as: :banking

  get 'management' => 'management#index', as: :management

  get 'simulation' => 'simulation#simulate', as: :simulation

  post 'getreide' => 'storage#crops', as: :crops
  post 'vieh' => 'storage#lifestock', as: :lifestock
  post 'technik' => 'storage#machinery', as: :machinery

  post 'getreide-verkaufen' => 'sales#sell_crops', as: :sell_crops
  post 'vieh-verkaufen' => 'sales#sell_lifestock', as: :sell_lifestock

  post 'getreide-anpflanzen' => 'production#sow_crops', as: :sow_crops
  post 'vieh-zuechten' => 'production#breed_lifestock', as: :breed_lifestock

  post 'getreide-kaufen' => 'trades#buy_crops', as: :buy_crops
  post 'vieh-kaufen' => "trades#buy_lifestock", as: :buy_lifestock

  post 'tilgen' => 'banking#amortize', as: :amortization
  post 'future' => 'banking#future', as: :futures
  post 'kredit' => 'banking#credit', as: :credits
  post 'versicherung' => 'banking#insurance', as: :insurance

  resources :personnels, only: [:index, :create]

end

app/controllers/production_controller.rb
class ProductionController < ApplicationController
  def index
    @crops = current_user.crops
    @lifestock = current_user.lifestocks
  end

  def sow_crops
    Crops.croplist.each do |type|
      crop = current_user.crops.select { |item| item.type == type}
      amount = crop[0].quantity + crop_params(type)[:sow].to_i
      if amount > 0
        crop[0].update!( quantity: amount, age: 0 )
      end
      cost = crop[0].unit_value * amount
      subtract_cash(cost)
    end

    redirect_to action: :index

  end

  def breed_lifestock
    Lifestock.lifestocklist.each do |type|
      lifestock = current_user.lifestocks.select { |item| item.type == type}
      amount = lifestock[0].quantity + lifestock_params(type)[:breed].to_i
      if amount > 0
        lifestock[0].update!( quantity: amount, age: 0 )
      end
      cost = (lifestock[0].unit_value/3) * amount
      subtract_cash(cost)
    end

    redirect_to action: :index
  end

  def crop_params(type)
    params.require(type).permit(:sow)
  end

  def lifestock_params(type)
    params.require(type).permit(:breed)
  end

  def subtract_cash(amount)
    cash = Game.current_game.cash
    Game.current_game.cash = cash - amount
    Game.current_game.save!
  end

end

app/views/production/index.html.erb
<div class="l-content">
  <h4 style="text-align: center;">Produktion</h4>
  <div class = "medium-9 columns">
    <div class="medium-12 columns">
      <h5>Felder</h5>

      <%= form_tag sow_crops_path do %>
        <table width="100%">
          <thead>
            <tr>
              <th width = 60px ></th>
              <th>Sorte</th>
              <th>Angeplfanzt:</th>
              <th>Wert gesamt</th>
              <th>Alter (in Saison)</th>
              <th>Anbauen</th>
            </tr>
          </thead>
          <tbody>
          <% @crops.each do |crop| %>
            <tr>
              <td><div class="<%= crop.type.downcase  %>-icon"></div></td>
              <td><b><%= crop.to_s %></b></td>
              <td><%= crop.quantity %></td>
              <td><%= number_to_currency(crop.value, unit: '€') %></td>
              <td><%= crop.age %></td>
              <td> Anbauen <%= number_field_tag "#{crop.type}[sow]", 0, step: 100%></td>
            </tr>
           <% end %>
          </tbody>
        </table>
      <%= submit_tag "Anbauen", class: "button" %>
      <% end %>
    </div>

    <div class="medium-12 columns">
      <h5>Vieh</h5>

      <%= form_tag breed_lifestock_path do %>
        <table width="100%">
          <thead>
            <tr>
              <th width = 60px ></th>
              <th>Vieh</th>
              <th>Menge</th>
              <th>Wert</th>
              <th>Alter:</th>
              <th>Nachzüchten</th>
            </tr>
          </thead>
          <tbody>
          <% @lifestock.each do |animal| %>
            <tr>
              <td><div class="<%= animal.type.downcase  %>-icon"></div></td>
              <td><b><%= animal.to_s %></b></td>
              <td><%= animal.quantity %></td>
              <td><%= number_to_currency(animal.value, unit: '€') %></td>
              <td><%= animal.age %></td>
              <td>Züchten <%= number_field_tag "#{animal.type}[breed]", 0, step: 10 %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <%= submit_tag "Züchten", class: "button" %>
      <% end %>
    </div>
  </div>
</div>