config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'management#index'

  get 'dashboard' => 'dashboard#index', as: :dashboard

  get 'einkauf' => 'trades#index', as: :trades
  get 'vertrieb' => 'sales#index', as: :sales
  get 'produktion' => 'production#index', as: :production
  get 'lager' => 'storage#index', as: :storage
  get 'bericht' => 'reports#index', as: :reports
  get 'bank' => 'banking#index', as: :banking

  get 'management' => 'management#index', as: :management

  get 'simulation' => 'simulation#simulate', as: :simulation

  post 'getreide' => 'storage#crops', as: :crops
  post 'vieh' => 'storage#lifestock', as: :lifestock
  post 'technik' => 'storage#machinery', as: :machinery

  post 'getreide-verkaufen' => 'sales#sell_crops', as: :sell_crops
  post 'vieh-verkaufen' => 'sales#sell_lifestock', as: :sell_lifestock

  post 'getreide-anpflanzen' => 'production#sow_crops', as: :sow_crops
  post 'vieh-zuechten' => 'production#breed_lifestock', as: :breed_lifestock

  post 'getreide-kaufen' => 'trades#buy_crops', as: :buy_crops
  post 'vieh-kaufen' => "trades#buy_lifestock", as: :buy_lifestock

  post 'tilgen' => 'banking#amortize', as: :amortization
  post 'future' => 'banking#future', as: :futures
  post 'kredit' => 'banking#credit', as: :credits
  post 'versicherung' => 'banking#insurance', as: :insurance

  resources :personnels, only: [:index, :create]

end

app/controllers/banking_controller.rb
class BankingController < ApplicationController

  def index
    @credits = game.credits
    @futures = game.futures
    @insurances = game.insurances.where.not(quantity: nil)
    @market_price = game.prices.inject({}) do |memo, record|
      key, value = [record.item_type, record.price]
      memo[key] = value
      memo
    end

    @insurance_price = game.insurances.inject({}) do |memo, record|
      key, value = [record.item, record.price_per_item]
      memo[key] = value
      memo
    end

  end

  def amortize
    credit = Credit.find_by(id: amortization_params[:id])
    subtract_from_cash(credit.principal + credit.accumulated_interest)
    Event.financial(credit, "Du hast in der letzten Saison einen Kredit über #{view_context.number_to_currency(credit.principal, unit: '€')} abbezahlt.")
    credit.destroy!

    redirect_to action: 'index'
  end

  def future
    future = game.futures.create(future_params)

    Liability.update(:future, "Terminvertrag für #{future.contractual_item} zum Preis #{view_context.number_to_currency(future.price, unit: '€')}")
    Event.financial(future, "Du hast in der letzten Saison einen Terminvertrag für #{future.contractual_item} zum Preis #{view_context.number_to_currency(future.price, unit: '€')} abgeschlossen")

    redirect_to action: 'index'
  end

  def credit
    binding.pry
    credit = game.credits.create(credit_params)

    Liability.update(:credit, "Kredit über #{view_context.number_to_currency(credit.principal, unit: '€')}")
    Event.financial(credit, "Du hast in der letzten Saison einen Kredit über #{view_context.number_to_currency(credit.principal, unit: '€')} aufgenommen.")
    add_to_cash(credit.principal)

    redirect_to action: 'index'
  end

  def insurance
    insurance = game.insurances.create(insurance_params)

    Liability.update(:insurance, "Versicherung für #{insurance.item} zum Preis #{view_context.number_to_currency(insurance.price_per_item, unit: '€')}")
    Event.financial(insurance, "Du hast in der letzten Saison einen Terminvertrag für #{insurance.item} zum Preis #{view_context.number_to_currency(insurance.price_per_item, unit: '€')} abgeschlossen")

    redirect_to action: 'index'
  end

  private

  def game
    Game.current_game
  end

  def credit_params
    parameters = params.require(:credit).permit(:principal, :duration, :installments)
    parameters.merge!({period: game.period, interest_rate: game.interest})
  end

  def insurance_params
    parameters = params.require(:insurance).permit(:item, :price_per_item, :quantity)
    parameters.merge!({period: game.period})
  end

  def future_params
    parameters = params.require(:future).permit(:contractual_item, :price, :settlement_period, :quantity)
    parameters.merge!({period: game.period})
  end

  def amortization_params
    params.require(:credit).permit(:id)
  end

  def add_to_cash(amount)
    cash = Game.current_game.cash
    Game.current_game.cash = cash + amount
    Game.current_game.save!
  end

  def subtract_from_cash(amount)
    cash = Game.current_game.cash
    Game.current_game.cash = cash - amount
    Game.current_game.save!
  end
end

app/views/banking/_form.html.erb
<div class="medium-9 columns">
    <h3>Kredit Aufnehmen</h3>
      <h4> Aktuelle Kreditkosten <%= number_to_percentage(Game.current_game.interest) %> </h2>
        <p>- Quelle <%= link_to "EZB cost of borrowing", "https://sdw.ecb.europa.eu/quickview.do?SERIES_KEY=124.MIR.M.U2.B.A2I.AM.R.A.2240.EUR.N"%></p>
          <%= form_tag credits_path do %>
          <table width="100%">
            <thead>
              <tr>
                <th>Kreditsume</th>
                <th>Laufzeit</th>
                <th>Raten</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= number_field_tag "credit[principal]", 0, step: 100%></td>
                <td><%= number_field_tag "credit[duration]", 0%></td>
                <td><%= number_field_tag "credit[installments]", 0%></td>
              </tr>
            </tbody>
          </table>
        <%= submit_tag "Kredit Aufnehmen", class: "button" %>
        <%end%>
    </div>
    <div class="medium-9 columns">
      <h3>Future Kaufen</h3>
        <%= tag("div", :data => {:dependencies => @market_price }, class: "futures") %>
          <%= form_tag futures_path do%>
            <table width="100%">
            <thead>
              <tr>
                <th> Vertragsgegenstand </th>
                <th> Preis pro Einheit </th>
                <th> Termin: in wie vielen Saisonen </th>
                <th> Menge </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= select_tag "future[contractual_item]", options_for_select(@market_price.keys, "Crops"), data: {contract: true} %></td>
                <td><%= number_field_tag "future[price]", 0, data: {price: true}%></td>
                <td><%= number_field_tag "future[settlement_period]", 0%></td>
                <td><%= number_field_tag "future[quantity]", 0, steps: 100%></td>
              </tr>
            </tbody>
          </table>
          <%= submit_tag "Termingeschäft Vereinbaren", class: "button" %>
        <% end %>
      </div>
    <div class="medium-9 columns">
      <h3>Versicherungen Kaufen</h3>
      <%= tag("div", :data => {:dependencies => @insurance_price }, class: "insurance") %> </div>
          <%= form_tag insurance_path do%>
            <table width="100%">
            <thead>
              <tr>
                <th> Vertragsgegenstand </th>
                <th> Preis pro Einheit </th>
                <th> Menge </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= select_tag "insurance[item]", options_for_select(@insurance_price.keys, "Crops"), data: {item: true} %></td>
                <td><%= number_field_tag "insurance[price_per_item]", 0, data: {itemprice: true} %></td>
                <td><%= number_field_tag "insurance[quantity]", 0, step: 100%></td>
              </tr>
            </tbody>
          </table>
          <%= submit_tag "Transaktion Tätigen", class: "button" %>
        <% end %>
      </div>

    </div>

app/views/banking/index.html.erb
<div class="l-content banking">
  <h4 style="text-align: center;">Bank</h4>
  <div class = "medium-12 columns">
    <div class="medium-4 columns">
      <h5>Liste Ihrer Kredite</h5>
      <% if !@credits.empty? %>
        <% @credits.each do |credit| %>
          <table>
            <thead>
              <th>Kreditsumme</th>
              <th>verbleibende Laufzeit</th>
              <th>Zinsen</th>
              <th>Tilgung</th>
            </thead>
            <tbody>
              <%= form_tag amortization_path do %>
                <%= hidden_field_tag "credit[id]", credit.id %>
                <tr>
                  <td> <%= number_to_currency(credit.principal, unit: '€') %> </td>
                  <td> <%= credit.duration %> </td>
                  <td> <%= credit.accumulated_interest %> </td>
                  <td> <%= submit_tag "Jetzt Tilgen", class: "button small"%> </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      <% else %>
        <div class= "content-box info" >
          Sie haben momentan keine Kredite aufgenommen
        </div>
      <% end %>
      </div>

      <div class="medium-4 columns">

        <h5>Liste Ihrer Futures (Termingeschäft)</h5>

      <% if !@futures.empty? %>
        <% @futures.each do |future| %>
          <table>
            <thead>
              <th>Vereinbarter Preis</th>
              <th>Menge</th>
              <th>Gesamt</th>
              <th>Termin</th>
              <th>Vertragsgegenstand</th>
            </thead>
            <tbody>
              <tr>
                <td> <%= future.price %></td>
                <td> <%= future.quantity %> </td>
                <td> <%= number_to_currency((future.price * future.quantity), unit: '€') %> </td>
                <td> <%= future.settlement_period %></td>
                <td> <%= future.contractual_item%></td>
              </tr>
            </tbody>
          </table>
        <% end %>
      <% else %>
        <div class= "content-box info" >
          Sie haben momentan keine Futures
        </div>
      <% end %>
      </div>
      <div class="medium-4 columns">

        <h5>Liste Ihrer Versicherungen</h5>

        <% if !@insurances.empty? %>
          <% @insurances.each do |insurance| %>
            <table>
              <thead>
                <th>Versicherungskosten pro Gegenstand</th>
                <th>Versicherter Gegenstand</th>
                <th>Menge</th>
                <th> Gesamtkosten </th>
              </thead>
              <tbody>
                <tr>
                  <td> <%= number_to_currency(insurance.price_per_item, unit: '€') %> </td>
                  <td> <%= insurance.item %> </td>
                  <td> <%= insurance.quantity %> </td>
                  <td> <%= number_to_currency((insurance.price_per_item * insurance.quantity), unit: '€') %> </td>
                </tr>
              </tbody>
            </table>
          <% end %>
      <% else %>
        <div class= "content-box info" >
          Sie haben momentan keine Versicherungen
        </div>
      <% end %>
      </div>
    </div>

  <div class = "medium-12 columns">
    <%= render 'form'%>


    <div class = "medium-3 columns">
      <div class= "content-box bank-content">
        Bei der Bank kannst du nicht nur Kapital leihen um Invesititionen zu finanzieren, sondern dich auch gegen allerlei Risiken absicher. Mit Futures kannst du deine Produkte zum aktuellen Marktpreis an einem bestimmten Termin in der Zukunft verkaufen und dich somit vor Preisschwankungen schützen. Mit Versicherung kannst du dich gegen Ernteausfälle und Schäden an deinen Produktionsmitteln absichern.
      <hr/></div>
    </div>
  </div>

</div>