config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'management#index'

  get 'dashboard' => 'dashboard#index', as: :dashboard

  get 'einkauf' => 'trades#index', as: :trades
  get 'vertrieb' => 'sales#index', as: :sales
  get 'produktion' => 'production#index', as: :production
  get 'lager' => 'storage#index', as: :storage
  get 'bericht' => 'reports#index', as: :reports
  get 'bank' => 'banking#index', as: :banking

  get 'management' => 'management#index', as: :management

  get 'simulation' => 'simulation#simulate', as: :simulation

  post 'getreide' => 'storage#crops', as: :crops
  post 'vieh' => 'storage#lifestock', as: :lifestock
  post 'technik' => 'storage#machinery', as: :machinery

  post 'getreide-verkaufen' => 'sales#sell_crops', as: :sell_crops
  post 'vieh-verkaufen' => 'sales#sell_lifestock', as: :sell_lifestock

  post 'getreide-anpflanzen' => 'production#sow_crops', as: :sow_crops
  post 'vieh-zuechten' => 'production#breed_lifestock', as: :breed_lifestock

  post 'getreide-kaufen' => 'trades#buy_crops', as: :buy_crops
  post 'vieh-kaufen' => "trades#buy_lifestock", as: :buy_lifestock

  post 'tilgen' => 'banking#amortize', as: :amortization
  post 'future' => 'banking#future', as: :futures
  post 'kredit' => 'banking#credit', as: :credits
  post 'versicherung' => 'banking#insurance', as: :insurance

  resources :personnels, only: [:index, :create]

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @crops = current_user.crops
    @lifestock = current_user.lifestocks
  end

  def sell_crops
    Crops.croplist.each do |type|
      crop = current_user.crops.select { |item| item.type == type}
      sold = crop[0].sold + crop_params(type)[:sold].to_i
      harvested = crop[0].harvested - sold
      amount = crop[0].quantity - sold
      crop[0].update!( sold: sold, harvested: harvested, quantity: amount )

      sale_amount = crop[0].sold * crop[0].unit_value
      Event.sales(crop , "Du hast in der letzten Saison Getreide im Wert von #{sale_amount} verkauft. Vergiss nicht neues anzupflanzen." )

      add_to_cash(sale_amount)
    end

    redirect_to action: :index
  end

  def sell_lifestock
    Lifestock.lifestocklist.each do |type|
      lifestock = current_user.lifestocks.select { |item| item.type == type}
      sold = lifestock[0].sold + lifestock_params(type)[:sold].to_i
      butchered = lifestock[0].butchered - sold
      amount = lifestock[0].quantity - sold
      lifestock[0].update!( sold: sold, butchered: butchered, quantity: amount )

      sale_amount = lifestock[0].sold * lifestock[0].unit_value
      Event.sales(lifestock , "Du hast in der letzten Saison Vieh im Wert von #{sale_amount} verkauft. Vergiss nicht neues nachzuzüchten." )

      add_to_cash(sale_amount)
    end

    redirect_to action: :index
  end

  private

  def crop_params(type)
    params.require(type).permit(:sold)
  end

  def lifestock_params(type)
    params.require(type).permit(:sold)
  end

  def add_to_cash(amount)
    cash = Game.current_game.cash
    Game.current_game.cash = cash + amount
    Game.current_game.save!
  end
end

app/views/sales/index.html.erb
<div class="l-content">
  <h4 style="text-align: center;">Vertrieb</h4>
  <div class = "medium-9 columns">
    <div class="medium-12 columns">
      <h5>Getreide</h5>

      <%= form_tag sell_crops_path do %>
        <table width="100%">
          <thead>
            <tr>
              <th width = 60px ></th>
              <th>Sorte</th>
              <th>Menge gesamt</th>
              <th>Geerntet:</th>
              <th>Wert</th>
              <th>Alter (in Saison)</th>
              <th>Verkaufen</th>
              <th>Bisher Verkauft</th>
            </tr>
          </thead>
          <tbody>
          <% @crops.each do |crop| %>
            <tr>
              <td><div class="<%= crop.type.downcase  %>-icon"></div></td>
              <td><b><%= crop.to_s %></b></td>
              <td><%= crop.quantity %></td>
              <td><%= crop.harvested %></td>
              <td><%= number_to_currency(crop.value, unit: '€') %></td>
              <td><%= crop.age %></td>
              <td> Verkaufen <%= number_field_tag "#{crop.type}[sold]", 0, step: 100, max: crop.harvested%></td>
              <td><%= crop.sold * crop.unit_value %> </td>
            </tr>
           <% end %>
          </tbody>
        </table>
      <%= submit_tag "Transaktion Tätigen", class: "button" %>
      <% end %>
    </div>

    <div class="medium-12 columns">
      <h5>Vieh</h5>

      <%= form_tag sell_lifestock_path do %>
        <table width="100%">
          <thead>
            <tr>
              <th width = 60px ></th>
              <th>Vieh</th>
              <th>Menge gesamt</th>
              <th>Geschlachtet</th>
              <th>Wert</th>
              <th>Alter:</th>
              <th>Verkaufen</th>
              <th>Bisher Verkauft</th>
            </tr>
          </thead>
          <tbody>
          <% @lifestock.each do |animal| %>
            <tr>
              <td><div class="<%= animal.type.downcase  %>-icon"></div></td>
              <td><b><%= animal.to_s %></b></td>
              <td><%= animal.quantity %></td>
              <td><%= animal.butchered %></td>
              <td><%= number_to_currency(animal.value, unit: '€') %></td>
              <td><%= animal.age %></td>
              <td>Verkaufen <%= number_field_tag "#{animal.type}[sold]", animal.sold, step: 100, max: animal.butchered%></td>
              <td><%= animal.sold * animal.unit_value %> </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <%= submit_tag "Transaktion Tätigen", class: "button" %>
      <% end %>
    </div>
  </div>
  <div class = "medium-3 columns">
    <div class= "content-box ">
      Hinweis nur vorher geerntetes Getreide bzw. geschlachtetes Vieh verkauft werden kann, verkauft wird immmer entweder zum Marktpreis oder zum Preis eventuell gekaufter Futures.
    <hr/></div>
  </div>
</div>