config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'management#index'

  get 'dashboard' => 'dashboard#index', as: :dashboard

  get 'einkauf' => 'trades#index', as: :trades
  get 'vertrieb' => 'sales#index', as: :sales
  get 'produktion' => 'production#index', as: :production
  get 'lager' => 'storage#index', as: :storage
  get 'bericht' => 'reports#index', as: :reports
  get 'bank' => 'banking#index', as: :banking

  get 'management' => 'management#index', as: :management

  get 'simulation' => 'simulation#simulate', as: :simulation

  post 'getreide' => 'storage#crops', as: :crops
  post 'vieh' => 'storage#lifestock', as: :lifestock
  post 'technik' => 'storage#machinery', as: :machinery

  post 'getreide-verkaufen' => 'sales#sell_crops', as: :sell_crops
  post 'vieh-verkaufen' => 'sales#sell_lifestock', as: :sell_lifestock

  post 'getreide-anpflanzen' => 'production#sow_crops', as: :sow_crops
  post 'vieh-zuechten' => 'production#breed_lifestock', as: :breed_lifestock

  post 'getreide-kaufen' => 'trades#buy_crops', as: :buy_crops
  post 'vieh-kaufen' => "trades#buy_lifestock", as: :buy_lifestock

  post 'tilgen' => 'banking#amortize', as: :amortization
  post 'future' => 'banking#future', as: :futures
  post 'kredit' => 'banking#credit', as: :credits
  post 'versicherung' => 'banking#insurance', as: :insurance

  resources :personnels, only: [:index, :create]

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="top-bar">
    <div class="content">Copyright (c) SchuetMuesBuss </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class= "header">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li>
          <% if current_user %>
            <div class="info">Cash ~ <%= current_user.game.cash %></div>
            <div class="info">Saison <%= current_user.game.period %></div>
          <% else %>
            <div class="info"> Wilkommen zum Simulation Game</div>
          <% end %>
        </li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li>
            <% if current_user %>
              <%= link_to "Verwaltung", management_path %>
            <% end %>
          </li>
          <li>
            <% if current_user %>
              <%= link_to "Bank", banking_path %>
            <% end %>
          </li>
          <li>
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            <% end %>
          </li>
        </ul>

      </section>
    </nav>
</div>

app/views/layouts/_sidebar.html.erb
<div class = "sidebar">

  <%= image_tag('farm_logo.png', class: 'farm-logo')%>
  <ul class = "navigation">
    <li class = "nav-item"> <%= link_to "Einkauf" , trades_path%> </li>
    <li class = "nav-item"> <%= link_to "Vertrieb" , sales_path%> </li>
    <li class = "nav-item"> <%= link_to "Produktion" , production_path%> </li>
    <li class = "nav-item"> <%= link_to "Lager & Betrieb" , storage_path%> </li>
    <li class = "nav-item"> <%= link_to "Personal" , personnels_path%> </li>
  </ul>
</div>

app/views/layouts/angular.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= render 'layouts/sidebar' %>
    <div data-ng-view></div>
    </div> <!-- /container -->
    <%= render 'layouts/footer'%>
    <%= javascript_include_tag "application"%>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application"%>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= javascript_tag do %>
      $(function(){
        height = $('.l-content').height();
        $('.sidebar').height( height + 100 );
      });
    <% end %>
    <%= render 'layouts/header'%>
    <%= render 'layouts/sidebar' %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>